name: hsc_chat
description: "Chat App project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  socket_io_client: ^3.1.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  permission_handler: ^12.0.1
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  mime: ^1.0.2
  http_parser: ^4.0.3
  path: ^1.8.3
  path_provider: ^2.0.15
  flutter_cache_manager: ^3.3.0
  just_audio: ^0.9.33
  video_player: ^2.5.1
  chewie: ^1.5.2
  pdfx: ^2.0.0
  google_fonts: ^6.3.2
  connectivity_plus: ^7.0.0
  flutter_svg: ^2.2.2
  url_launcher: ^6.1.10
  video_thumbnail: ^0.5.1
  gallery_saver_plus: ^3.2.9
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
